job_tiles_with_categories = {
    # 'website Development' : ['WordPress Developer' , 'WordPress Theme Developer' , 'WordPress Plugin Developer', 'WordPress Frontend Developer' ,
    #                            'WordPress Backend Developer' , 'WordPress Theme Designer' , 'WordPress Consultant' , 'WordPress Support Engineer',
    #                            'Joomla Developer' , 'Joomla Frontend Developer' , 'Joomla Template Developer' , 'Joomla Extension Developer' ,
    #                            'Joomla Site Builder' , 'Joomla Consultant' , 'Joomla Architect' , 'Joomla Support Engineer' ,
    #                            'Drupal Developer' , 'Drupal Frontend Developer' , 'Drupal Backend Developer' , 'Drupal Module Developer' , 'Drupal Site Builder'
    #                            'Drupal Consultant' , 'Drupal Architect' , 'Drupal Support Engineer','Contentful Developer' , 'HTML/CSS Developer' , 'Frontend Developer' ,
    #                            'Webmaster' , 'Web Administrator' , 'Web Analyst' , 'Web Architect' , 'Web Consultant' , 'Web Coordinator' , 'Web Editor' ,
    #                            'Web Integrator' , 'Web Services Developer' , 'Web Accessibility Specialist' , 'Performance Optimization Specialist'],

    # 'Web App Development / Javascript' : ['Angular Developer' , 'Angular Frontend Developer' , 'Angular UI Developer' , 'Angular Architect' , 'Angular Consultant' ,
    #                                       'Angular Team Lead' , 'Angular Full stack Developer' , 'React Developer' , 'ReactJS Developer' , 'React Frontend Developer' ,
    #                                       'React UI Developer' , 'React Architect' , 'React Consultant' , 'React Team Lead' , 'React Full stack Developer',
    #                                       'Vue.js Developer' , 'Vue.js Frontend Developer' , 'Vue.js UI Developer' , 'Vue.js Architect' , 'Vue.js Consultant' ,
    #                                       'Vue.js Team Lead' , 'Vue.js Full stack Developer' , 'Ember.js Developer' , 'Ember.js Frontend Developer' , 'Ember.js UI Developer',
    #                                       'Ember.js Architect' , 'Ember.js Consultant' , 'Ember.js Team Lead' , 'Ember.js Full stack Developer', 'Backbone.js Developer' ,
    #                                       'Backbone.js Frontend Developer' , 'Backbone.js UI Developer' , 'Backbone.js Architect' , 'Backbone.js Consultant' , 'Backbone.js Team Lead',
    #                                       'Backbone.js Full stack Developer' , 'Meteor.js Developer' , 'Meteor.js Full-stack Developer' , 'Meteor.js Consultant' , 'Meteor.js Team Lead' ,
    #                                       'Node.js Developer' , 'Node.js Backend Developer' , 'Node.js Architect' , 'Node.js Consultant' , 'Node.js Team Lead' , 'Node.js Full stack Developer',
    #                                       'NEXT.js Developer' , 'NEXT.js Architect' , 'NEXT.js Consultant' , 'NEXT.js Team Lead' , 'NEXT.js Full stack Developer' , 'JavaScript Developer' ,
    #                                       'Web Application Developer' , 'Web App Developer' , 'TypeScript Developer' , 'jQuery Developer' , 'Web Services Developer' ,
    #                                       'RESTful API Developer', 'SOAP Developer' , 'Frontend Architect' , 'Responsive Web Developer' , 'Progressive Web App (PWA) Developer' ,
    #                                       'Serverless Developer' , 'Real-time Applications Developer' , 'Microservices Architect' , 'Microservices Developer' , 'Frontend Developer' ,
    #                                       'Full Stack Developer' , 'MEAN Stack Developer (MongoDB, Express.js, Angular, Node.js)' , 'MERN Stack Developer (MongoDB, Express.js, React, Node.js)' ,
    #                                        ],
    # 'Backend Engineering' : ['.NET Developer' , 'ASP.NET Developer' , 'C# Developer' , 'VB.NET Developer' , 'Windows Forms Developer' , 'WPF Developer' , 'ASP.NET MVC Developer' ,
    #                          'Entity Framework Developer' , 'ASP.NET Backend Developer' , 'ASP.NET Architect' , 'ASP.NET Consultant' , 'ASP.NET Team Lead' , 'ASP.NET Full Stack Developer' ,
    #                          'ASP.NET Developer' , 'ASP.NET Engineer' , 'Java Developer' , 'J2EE Developer' , 'Spring Framework Developer' , 'Hibernate Developer' , 'JavaFX Developer' ,
    #                          'Java Swing Developer' , 'Java Architect' , 'Java Full Stack Developer' , 'Java Web Services Developer' , 'Java Enterprise Developer' , 'Python Developer',
    #                          'Django Developer' , 'Flask Developer' , 'Python Full Stack Developer' , 'Python Web Developer' , 'Python Scripting Developer' , 'Scientific Computing Developer (Python)',
    #                          'SQL Developer' , 'Database Administrator (DBA)' , 'Data Engineer' , 'Database Architect' , 'Database Analyst' , 'Data Warehouse Developer' ,
    #                          'Business Intelligence Developer' , 'ETL Developer' , 'Oracle Developer' , 'MySQL Developer' , 'PostgreSQL Developer' , 'MongoDB Developer' ,'SQL Engineer',
    #                          'Database Developer' , 'Ruby on Rails Backend Developer' , 'Ruby on Rails Architect' , 'Ruby on Rails Consultant' ,'Ruby on Rails Team Lead' , 'Ruby on Rails Full stack Developer',
    #                          'Ruby Developer' ,'Ruby on Rails Developer' , 'Ruby Full Stack Developer' , 'Ruby Web Developer' , 'Ruby API Developer' , 'Ruby Scripting Developer' ,
    #                          'Ruby Consultant' , 'Django Backend Developer' , 'Django Architect' , 'Django Consultant' , 'Django Team Lead' , 'Django Full Stack Developer' ,
    #                          'Flask Backend Developer' , 'Flask Architect' , 'Flask Consultant' ,'Flask Consultant' , 'Flask Team Lead' ,'Flask Full Stack Developer' , 'PHP Developer',
    #                          'Laravel Developer' , 'Symfony Developer' , 'CodeIgniter Developer' , 'PHP Full Stack Developer' , 'PHP Web Developer' , 'PHP Architect' , 'PHP Consultant',
    #                          'Custom PHP Developer' , 'API Developer' , 'Integration Engineer' , 'API Architect' , 'API Engineer' , 'Integration Programmer' , 'Integration Support Engineer' ,
    #                          ],
    # 'Mobile App Development' : ['iOS Developer' , 'Swift Developer' , 'Objective-C Developer', 'Android Developer' , 'Kotlin Developer' , 'Java Developer' ,
    #                             'React Native Developer' ,'Flutter Developer' , 'Dart Developer' , 'Xamarin Developer' , 'Mobile App Engineer' ,
    #                             'Mobile Application Engineer' , 'Mobile App Developer','Mobile Application Developer' , 'Mobile Architect' , 'Mobile Game Developer' ,
    #                             'Mobile Architect' , 'Mobile App Architect' , 'Cross-Platform App Developer','Hybrid Mobile App Development' ,
    #                             'Mobile Performance Engineer' , 'Mobile Security Specialist' , 'Mobile Support Engineer'],
    # 'General Engineering' : ['Software Engineer' , 'Custom Software Developer' , 'Solutions Architect' , 'Application Developer','App Developer' , 'Desktop Application Architect' ,
    #                          'Desktop Application Developer' , 'Windows Application Developer' , 'Linux Application Developer' , 'macOS Application Developer' , 'Enterprise Software Developer',
    #                          'Systems Analyst' , 'Enterprise Integration Architect' ,'Enterprise Software Consultant' , 'Enterprise Software Support Engineer' , 'Enterprise Architect',
    #                          'Enterprise Integration Specialist' , 'Enterprise Security Developer' , 'Software Architect' , 'Typescript Developer' , 'Application Support Engineer' ,
    #                          'Technical Support Engineer' , 'Software Maintenance Engineer' , 'Support Specialist' , 'Support Analyst' , 'Support Consultant', 'Support Coordinator' ,'Support Manager' ,
    #                          'Support Team Lead' , 'Application Support Specialist' , 'Application Support Analyst' , 'Application Support Consultant',
    #                          'Application Support Coordinator' , 'Application Support Manager' ,'Technical Support Specialist',
    #                          'Technical Support Analyst' , 'Technical Support Analyst' , 'Technical Support Coordinator',
    #                          'Technical Support Manager' , 'Maintenance Engineer' , 'Maintenance Specialist' ,'Maintenance Coordinator',
    #                          'Maintenance Manager' , 'Software Consultant' , 'Technical Consultant' , 'Software Solution Architect' ,
    #                          'Technology Solutions Consultant' , 'Enterprise Consultant' , 'Change Management Consultant' , 'Software Implementation Consultant'],
    #
    # 'DevOps (DevOps & General Cloud Campaign)' : ['DevOps Engineer' , "Monitoring and Alerting Engineer" , 'DevOps Consultant' , 'DevOps Architect' , 'Docker/Kubernetes Engineer' , 'Jenkins Engineer' , 'GitOps       Engineer' , 'Kubernetes Developer' , 'Azure Developer' , 'Serverless Developer' , 'Containerization Engineer' , 'Cloud Developer' , 'Cloud Engineer' , 'Cloud Architect' , 'Cloud Solutions Architect' ,'Cloud Infrastructure Engineer' , 'Cloud Security Engineer' , 'Cloud Operations Engineer','Cloud Automation Engineer' , 'Cloud Consultant' , 'Cloud Project Manager' , 'Cloud Support Engineer' , 'Cloud Systems Administrator' , 'Cloud Integration Specialist' , 'Cloud Migration Specialist' , 'Cloud Analytics Developer' , 'Cloud AI Engineer' , 'Cloud Data Engineer', 'Cloud DevSecOps Engineer' , 'Cloud Data Engineer' , 'Cloud DevSecOps Engineer' , 'Cloud Governance Specialist' , 'Cloud Cost Optimization Engineer' , 'Cloud Compliance Specialist' , 'Cloud Infrastructure Architect' ,'Cloud Platform Infrastructure Specialist' , 'Cloud Security Architect' , 'Cloud Virtualisation Specialist' , 'Cloud Automation Specialist' , 'Cloud Compliance Specialist' , 'Cloud Infrastructure Architect' , 'Cloud Platform Infrastructure Specialist' , 'Cloud Security Architect' , 'Cloud Virtualisation Specialist' , 'Cloud DevOps Engineer' , 'Principal Consultant Cloud Professional Services' , 'Head Of Cloud Infrastructure' , 'Head Of Cloud Strategy And Architecture' , 'Release Engineer'],
    #
    # 'AI/ML' : ['Data Analyst', 'Data Visualization Developer' , 'Data Warehousing Specialist' , 'Data Mining Specialist' , 'Data Modeller' , 'Data Consultant' , 'Data Product Evangelist' ,'Data Specialist',
    #            'Data Scientist Machine Learning', 'Data Strategist' , 'Data Protection Technical Advisor' , 'Data Quality Analyst' , 'Data Scientist' , 'Data Analyst/scientist' , 'Big Data Architect','Big Data Analytics / Etl Developer' ,'Big Data Engineer' , 'Business Intelligence Developer' , 'Business Intelligence Analyst' , 'Business Analytics Consultant' ,'ETL Developer' ,'Data Governance Specialist','Predictive Analytics Developer' , 'Business Intelligence Bi Consultant' ,'Enterprise Data Architect','Ai/ml Architect' , 'Machine Learning Researcher' ,'Ai Conversational Designer',
    #            'Machine Design Engineer' , 'Scientific Data Analyst / Algorithms Researcher' , 'Developer Business Intelligence' , 'Principle Data Scientist Machine Learning' , 'AI Researcher' ,'Business Intelligence Bi Analyst' , 'Big Data/hadoop Developer' , 'Competitive Intelligence Analyst' , 'Ai/ml Engineer' ,'Solutions Consultant Ai' , 'Bi And Data Analyst' , 'Machine Learning Specialist',
    #            'AI Scientist' , 'Business Intelligence' ,'Principle Data Architect' , 'Data/business Intelligence Analyst' , 'Business Data Analyst' , 'Machine Vision Application Engineer' ,'Machine Vision Application Engineer' , 'Machine Learning Engineer' , 'Machine Learning Research Engineer' , 'AI Engineer' , 'Deep Learning Engineer' , 'Machine Design' ,'Machine Researcher' , 'AI Programmer',
    #            'Lead AI' , 'AI Developer' , 'Data Scientist ' ,'AI Success' , 'Risk and Analytics' , 'AI Expert' , 'Intelligence Analyst' , 'Big Data & AI Researcher' ,'AI Consultant','AI Experience',
    #            'AI Operations' , 'Algorithm Development' , 'AI Business Analyst' , 'Cyber AI' , 'Data Architect' , 'AI Specialist' , 'AI Intern' , 'Cognitive Scientist' , 'Cognitive Engineer' , 'AI Learning Engineer' , 'Data Evangelist' , 'AI Analyst' , 'AI Solutions Architect' , 'AI Deep Learning' ,'Senior Data Engineer' ,'Principal AI Researcher' , 'AI Full Stack' , 'Intelligence Engineer' ,'AI Data Engineer' , 'AI Evangelist' , 'ML Evangelist' ,'AI Developer' , 'Advanced AI Analytics' , 'AI Technical Advisor'],

    # 'Ecommerce Experts' : ['Magento Developer' , 'Magento Frontend Developer' , 'Magento Backend Developer' , 'Magento Theme Developer' , 'Magento Extension Developer' ,'Magento Consultant' , 'Magento Architect',
    #                        'Magento Support Engineer' , 'WooCommerce Developer' , 'WooCommerce Theme Developer' , 'WooCommerce Plugin Developer' , 'WooCommerce Frontend Developer' ,'WooCommerce Backend Developer' ,
    #                        'WooCommerce Consultant' , 'WooCommerce Support Engineer','PrestaShop Developer' , 'BigCommerce Developer' , 'OpenCart Developer' , 'Hybris Developer' , 'E-commerce Architect' , 'Shopping Cart Developer' , 'Order Management Developer' , 'E-commerce Analytics Developer' , 'E-commerce Developer' , 'Online Store Developer' , 'E-commerce Consultant' , 'E-commerce Programmer' ,'E-commerce Support Engineer' , 'E-commerce Systems Analyst'],
    # 'QA' : ['QA Analyst' ,'QA Consultant' , 'QA Manager' ,'QA Architect' , 'QA Automation Specialist' , 'QA Performance Engineer' , 'QA Security Engineer' , 'QA Test Data Engineer' , 'QA Test Planning Engineer',
    #         'QA Test Strategy Manager' , 'QA Test Reporting Specialist' , 'Quality Assurance Engineer' , 'QA Automation Engineer' ,'Software Tester' , 'Test Automation Engineer' , 'Automation Engineer'],

    'Management' : ['Project Manager' , 'Techinical Project Manager ' , 'Scrum Master ' , 'Project Manager ' , 'Product Owner ' ,'IT Manager'],

    # 'NoCode Web Development' : ['Wix Developer', 'Wix Website Designer' , 'Wix App Developer' , 'Wix Front-end Developer' , 'Wix Template Designer' , 'Wix Consultant' , 'Wix Support Engineer' , 'Squarespace Developer',
    #                             'Squarespace Website Designer' , 'Squarespace Template Developer' , 'Squarespace Front-end Developer' , 'Squarespace Consultant' , 'Squarespace Support Engineer',
    #                             'Weebly Developer' , 'Weebly Website Designer' , 'Weebly Template Developer' , 'Weebly Front-end Developer' , 'Weebly Consultant' , 'Weebly Support Engineer',
    #                             'Webflow Developer' , 'Webflow Website Designer' ,'Webflow Template Developer' , 'Webflow Front-end Developer' , 'Webflow Consultant' , 'Webflow Support Engineer' , 'Webflow Designer'],
    #
    # 'GCP' : ['Google Cloud Architect' , 'Google Cloud Engineer' , 'Google Cloud Consultant' , 'Google Cloud Platform Architect' , 'Google Cloud Instructor' ],
    #
    # 'AWS' : ['Amazon Docker' , 'AWS Architect' , 'AWS Big Data' , 'AWS Cloud Architect' , 'AWS Cloud Engineer' , 'AWS Data Engineer' , 'AWS DevOps' , 'AWS Infrastructure' , 'AWS Security' , 'AWS Solutions' , 'AWS SysOps',
    #          'AWS Networking' , 'AWS Redshift' , 'AWS Integrator' , 'AWS Enterprise' ,'AWS Solutions Architect' , 'Big Data AWS' , 'Azure Cloud Infrastructure Engineer' , 'Aws Developer' , 'Lead Developer Aws Cloud',
    #          'Aws Connect Architect Developer' , 'Devsecops / Aws Operations Engineer' , 'Security Engineer Aws' ,'Aws Sysops Devops Architect' , 'Devops/aws Engineer' , 'Aws Big Data Engineer' ,'Aws Platform Engineer/devops',
    #          'Aws Devops Engineer'],
    # #
    # 'Salesforce Development' : ['Salesforce Administrator' , 'Salesforce Consultant' , 'Salesforce Architect' , 'Salesforce Lightning Developer' , 'Salesforce Integration Developer' , 'Salesforce CPQ Developer',
    #                             'Salesforce Marketing Cloud Developer' , 'Salesforce Commerce Cloud Developer' , 'Salesforce Community Cloud Developer' , 'Salesforce Service Cloud Developer' , 'Salesforce Data Analyst',
    #                             'Salesforce Data Migration Specialist' , 'Salesforce Business Analyst' , 'Salesforce Solution Architect' , 'Salesforce Data Specialist' , 'Salesforce Admin Support Analyst' ,
    #                             'Salesforce Marketo Admin' , 'Salesforce Engineer' , 'Implementation Consultant Salesforce' , 'Salesforce Commercial Operations Manager' , 'Salesforce Functional Consultant' ,
    #                             'Salesforce Operations Support Lead' , 'Salesforce Application Consultant' , 'Salesforce Marketing Consultant' , 'Salesforce Application Developer' , 'Salesforce Marketing Cloud Technical Architect',
    #                             'Salesforce Technical Product Owner' , 'Salesforce Analyst' , 'Lightning Salesforce Developer' , 'Salesforce Developer'],
    #
    # 'Shopify Custom Development' : ['Shopify Developer' , 'Shopify Theme Developer' , 'Shopify App Developer' , 'Shopify Front-end Developer' , 'Shopify Store Setup Specialist' , 'Shopify Consultant',
    #                                 'Shopify Support Engineer'],
    
    # 'General Design' : ['ART Director' , 'Branding And Packaging Designer' , ' Creative Designer' , 'Design Director' , 'Design Lead' , 'Designer/multimedia Specialist' , 'Multimedia Specialist' , 'Digital Designer',
    #                     'Director Of Design' , 'Intermediate Designer' , 'Multimedia Content Designer' , 'Multimedia Designer' , 'Principal Designer' , 'Visual Designer' , 'Design Specialist' , 'Digital Designer',
    #                     'Visual Communicator' , 'Data Visualization Specialist' 'Visual Storyteller' , 'Creative Director' , 'Creative Coordinator' , 'Design Manager' , 'Design Director' , 'Design Team Lead'],
    #
    # 'Branding' : ['Brand Strategist' , 'Branding Expert' , 'Visual Identity Designer' , 'Branding Designer' , 'Logo Designer' , 'Brand Designer' , 'Brand Identity Specialist' , 'Brand Strategist',
    #               'Corporate Identity Designer' , 'Brand Experience Designer' , 'Brand Identity Developer'],
    #
    # 'UI/UX' : ['Advanced Ux Researcher' , 'App Designer' , 'Associate Product Designer' , 'Digital Product Designer' , 'Front-End Designer' , 'Graduate Ux Designer' , 'Intermediate ui' , 'Intermediate ux' ,
    #            'Mobile Designer' , 'Mobile Interaction Designer' , 'Mobile Interface Designer' , 'Mobile UI Designer' , 'Mobile User Experience Designer' , 'Mobile User Interface Designer' , 'Product Designer',
    #            'UI Designer' , 'UI Product Designer ' , 'User Experience (UX) Designer' , 'User Interface (UI) Designer' , 'UX Designer' , 'UX Product Designer' , 'UX User Designer' , 'UX/UI Artist' , 'UX/UI Artist',
    #            'UX/UI Designer' , 'Web Designer' , 'Web Designer / Data Visualization Analyst' , 'Webflow Designer' , 'UI/UX Designer' , 'UX Designer' , 'Interaction Designer' , 'Information Architect' ,
    #            'Usability Specialist' , 'User Researcher' , 'User Interface Designer' , 'Product Designer' , 'Service Designer' , 'UX Researcher' , 'UX Strategist' , 'Email Marketing Designer' , 'Interactive Designer'],
    #
    # 'Graphic Design' : ['Content Designer' , 'Design Associate' , 'Graphic Designer' , 'Packaging Designer' , 'Social Media Graphic Designer' , 'Senior Graphic Designer ' , 'Visual Communication Designer',
    #                     'Print Designer' , 'Digital Designer' , 'Presentation Designer' , 'Packaging Designer' , 'Print Designer' , 'Print Specialist' , 'Packaging Designer' , 'Social Media Designer' ,
    #                     'Presentation Designer' , 'Slidedeck Designer'],
    #
    # 'Animation and Motion Designer' : ['3D Animator' , '3D Designer' , '3D Design Associate' , '2D Animator' , '2D Designer' , '2D Desgin Associate' , '2D/3D Animator' , '2D/3D DesignerI' , '2D/3D Design Associate',
    #                                    'Animation Director ' , 'Animator' , 'Lead Animator' , 'Motion Designer' , 'Motion Graphic Designer' , 'Social Motion Digital Designer' , 'Social Motion Digital Animator',
    #                                    'Video Editor Multimedia Designer' , 'Visual Effects Artist' , 'Storyboard Artist' , 'Motion Graphics Designer'],

    # 'LiveLeads' : ['Demand Generation Manager' ,  'Demand Generation Specialist' , 'Lead Research Representative' , 'Lead Researcher' , 'Lead Generation Specialist' , 'Lead Management' ,
    #                'Lead Nurturing' , 'Lead Qualification' , 'Lead Research' , 'Sales Lead Generation' , 'Lead Generation Specialist' , 'Lead Generation Manager (Digital)' , 'Lead Generation Specialist',
    #                'Lead Qualification Representative' , 'Data Researcher' , 'Lead Generation Manager' , 'Lead Nurturing Specialist' , 'Lead Analyst'],
    #
    # 'B2B Growth' : ['Account Coordinator' , 'Account Director' , 'Account Executive' , 'Account Executive / Account Manager' , 'Account Executive Financial Services' , 'Account Executive Partnership Marketing',
    #                 'Account Manager' , 'Account Manager Client Success' , 'Account Manager/strategist Social And Content' , 'Account Representative' , 'Account Specialist' , 'Accounting Manager' , 'Scheduling Manager',
    #                 'Email Developer' , 'Email Marketing' , 'Email Marketing Account Manager' , 'Email Marketing Coordinator' , 'Email Marketing Manager' , 'Email Marketing Specialist' , 'Email Specialist',
    #                 'Digital Automotive Account Manager' , 'Digital Account Manager' , 'Digital Marketing Account Manager' , 'Business Development Manager' , 'Digital Marketing Account Manager' ,
    #                 'Enterprise Account Executive' , 'Enterprise Operations Manager' , 'Enterprise Sales' , 'General Sales Manager' , 'Group Sales' , 'Healthcare Sales' , 'Industrial Sales' , 'Inside Sales',
    #                 'Inside Sales Associate' , 'Inside Sales Rep' , 'Inside Sales Representative' , 'Insurance Sales ' , 'Key Accounts' , 'Named Account Manager' ,     "Manager CRM",
    #                 "Marketing Account Executive","Appointment Setting","SAppoint","Appointment Schedulers","Business Development","Business Development Associate","Business Development Director","Business Development Director Sales","Business Development Executive","Business Development Manager","Business Development Representative","Business Development Specialist", "Business Operations","Business Operations Manager", "Business Sales Associate", "Junior Account Manager", "Account Executive", "Sales Development Representative", "Sales Development Representative SDR", "Senior Sales Development Representative", "Email Deliverability Specialist", "Key Account Manager", "Senior Account Executive", "Senior Business Development Manager", "Senior Growth Manager", "Head of Sales Development", "Director of Business Development", "Director of Growth", "Vice President of Business Development", "Vice President of Growth", "Chief Growth Officer", "Strategic Partnerships Manager","Development Coordinator","Email Campaign Manager","Email Automation Specialist","Drip Campaign Manager","SaaS Sales Representative","Technical Sales Specialist","Cybersecurity Sales Specialist", "Cloud Sales Specialist", "IT Services Sales Consultant", "Software Sales Engineer", "Pharmaceutical Account Manager", "Email Performance Marketing Manager" ],
    #
    # 'General Sales' : ["Admin Sales","Sales Account Executive","Sales Admin","Sales Advisor","Sales And Catering Manager","Sales And Community Development Manager","Sales And Marketing Manager","Sales Assistant",
    #                 "Sales Associate","Sales Consultant", "Sales Coordinator","Director of Sales","Sales Engineer","Sales Director","sales executive","Sales Manager","Sales Marketing","Sales Operation",
    #                 "Sales Operations Manager","Sales Ops Engineer","Sales Professional","Sales Service Representative","Sales Specialist","Sales Support Specialist","B2B Sales","Sales Associate",
    #                 "Junior Sales Representative","Marketing and Sales Coordinator",
    #                 "Sales Engineer","Channel Sales Manager","Sales Operations Analyst","Senior Sales Representative","National Sales Manager","Regional Sales Manager","Sales Enablement Manager",
    #                 "Customer Success Manager","Commercial Manager","Software Sales","Specialty Sales","Crm Manager","It Technical Sales Apprentice","Vice President of Sales","Digital Manager","Digital Manager","Digital Marketing Sales Analyst","Direct Sales","Director Of Sales","Distribution Sales","District Sales","Manager Business Solutions","Marketing Assistant/sales Proposal Designer",
    #                 "Sales Representative","Territory Sales Manager","Sales Consultant","Chief Revenue Officer","Chief Sales Officer","Enterprise Sales Representative","SaaS Sales Representative","Technical Sales Representative","Pharmaceutical Sales Representative","Medical Device Sales Representative","Industrial Sales Representative","Technical Sales Representative","Territory Manager","Technical Account Manager", "Strategy And Business Development Specialist","Sales Director Anz","Sales","Pharmaceutical Sales Representative","Medical Device Sales Representative","Biotech Sales Specialist","Healthcare IT Sales Representative", "Clinical Sales Specialist", "Industrial Sales Representative", "Manufacturing Sales Representative", "Oil & Gas Sales Specialist",
    #                 "Construction Equipment Sales Manager","Technical Product Sales Representative","Financial Services Sales Consultant","Insurance Sales Representative","Mutual Fund Sales Specialist",
    #                 "Wealth Management Sales Consultant","Institutional Sales Specialist","Real Estate Sales Agent","Commercial Property Sales Manager","Real Estate Investment Sales Specialist","Mortgage Sales Representative","Media Sales Representative","Broadcasting Sales Manager","Digital Media Sales Consultant","Sponsorship Sales Manager","Telecommunication Services Sales Representative",
    #                 "Mobile Solutions Sales Specialist","Broadband Sales Consultant","Network Equipment Sales Manager","Proposal Writer","Account Executive","Sales Manager","Sales Team Leader","Business Development Representative","Inside Sales Representative","Inside Sales Representative","Business Development Representative","Sales Representative","Account Manager"]
    #


    
}

keywordfilter = [
                #'Application Developer', 'Software Developer', 'Chief Technology', 'Application Engineer',
                 # 'Agile Developer',
                 # '.net developer', 'Full Stack Developer', 'iOS Developer', 'Android Developer',
                 # 'React Native Developer', 'React Developer',
                 # 'React.js Developer', 'MERN Stack Developer', 'Software Architect', 'Java Developer', 'JS Developer',
                 # 'UI Engineer',
                 # 'Web Administrator', 'Web Engineer', 'Information Architect', 'IT Manager', 'Python Django',
                 # '.net developer', '.net engineer',
                 # '.net analyst', '.net programmer', 'Angular Developer', 'php developer', 'php programmer',
                 # 'full stack developer', 'Software Engineer',
                 # 'Database Administrator', 'Computer Programmer', 'Database Engineer', 'Data Modeler',
                 # 'Frontend Developer', 'node.js Developer',
                 # 'Backend Developer', 'Backend Software', 'Frontend Software',
                 # 'Full stack Software', 'Full Stack Web', 'Full Stack Java', 'Ruby Developer', 'ROR Developer',
                 # 'GraphQL Developer',
                 # 'HTML developer', 'HTML CSS Developer', 'HTML Engineer', 'CSS Developer', 'React Engineer',
                 # 'React Software Developer',
                 # 'ReactNative Developer', 'ReactNative Software Developer', 'Master Software Engineer', 'C# Developer',
                 # 'C# Software Engineer',
                 # 'Flutter Developer    ', 'Junior Android Developer', 'Android Software Engineer',
                 # 'Android Mobile Applications Developer',
                 # 'iOS Software Developer', 'iOS Software Engineer', 'iOS Mobile Developer', 'iOS Swift Developer',
                 # 'Java Developer', 'Kotlin Developer',
                 # 'Java Architect', 'Java Programmer', 'JS Software ', 'UX Frontend', 'Python Developer',
                 # 'Software Development', 'Web Developer',
                 # 'Mobile SDET', 'SDET Consultant', 'Technical Operations', 'Interface Developer', 'UI/UX Engineer',
                 # 'QA Engineer', 'UI Developer',
                 # 'UX Developer', 'Application Analyst', 'Angular JS', 'Digital Designer', 'creative director',
                 # 'Design Associate', 'Design Engineer',
                 # 'Front-End Designer', 'Graphic Designer', 'motion designer', 'web designer', 'Branding Expert',
                 # 'UI Artist', ' UI/UX Manager',
                 # 'UI/UX Designer', 'UI/UX Developer', 'Creative Director', 'Animation Director', 'Animation Producer',
                 # 'Motion Designer',
                 # 'Product Designer', 'UI Architect', 'UX Architect', 'UX Researcher', 'Creative Designs', 'UI Audit',
                 # 'Ux Audit', 'Brand design',
                 # 'Contract Designer', 'Design Lead', 'Design Head', '3D Animator', 'Principal Designer',
                 # 'Visual Designer', 'Systems Designer',
                 # 'Multimedia Designer', 'Head UX', 'Head Design', 'Head UI', 'Mobile Designer', 'App Designer',
                 # 'Digital Design Strategist',
                 # 'Account Executive', 'Account Manager', 'Account Manager/Executive', 'Specialty Sales Representative',
                 # 'Advertising Sales Representative',
                 # 'Advertising sales Representative.', 'Area Sales Manager', 'Assistant Account Executive',
                 # 'Automotive Sales Representative',
                 # 'Strategic Account Manager', 'business developer', 'Business Development Analyst',
                 # 'Business Development Associate',
                 # 'Business Development Director', 'Business Development Executive', 'Business Development Manager',
                 # 'Business Development Representative',
                 # 'Campaign manager', 'Channel Partner Sales Executive', 'Corporate Sales', 'Account Executive',
                 # 'Technical Sales Representative',
                 # 'Demand generation manager', 'Direct Sales Manager', 'Direct Salesperson',
                 # 'Director of email marketing', 'Director of Inside Sales',
                 # 'Director of market research', 'Director of National Sales', 'Director of sales',
                 # 'Distribution Sales Representative',
                 # 'District Sales Manager', 'Territory Business Manager', 'Territory Manager', 'Territory Sales Manager',
                 # 'Territory Sales Representative',
                 # 'Email developer', 'Email marketer', 'Email marketing strategist', 'Email operations manager',
                 # 'Enterprise Resources Planning RepresentativePrw08xccXh8vCzanCr', 'Enterprise Sales Representative',
                 # 'Equipment Sales Representative',
                 # 'Equipment Sales Specialist', 'Executive Vice President of Sales', 'Financial Advisor',
                 # 'Financial Planner', 'Financial Sales Assistant',
                 # 'Fixed Income Specialist', 'Franchise Development Manager', 'Group and Events Sales Coordinator',
                 # 'Group Sales Manager',
                 # 'Healthcare Sales Representative', 'Industrial Sales Representative', 'Industry Representative',
                 # 'Inside Sales Manager',
                 # 'Inside Sales Representative', 'Inside Salesperson', 'Insights analyst',
                 # 'Insurance Sales Representative', 'Investments Representative',
                 # 'Key Account Manager', 'Major Accounts Manager', 'Manager, Business Development',
                 # 'Market Development Manager', 'Salesperson',
                 # 'Market research interviewer', 'Market Research specialist', 'Marketing Associate',
                 # 'Wealth Management Advisor', 'Wholesale Sales Manager',
                 # 'Medical Sales Representative', 'National Accounts Sales Analyst',
                 # 'National Accounts Sales General Manager', 'National Accounts Sales Representative',
                 # 'National Sales Manager', 'Outside Sales Representative', 'Product research analyst',
                 # 'Qualitative research assistant', 'Regional Account Manager', 'Regional Dealer Recruiter',
                 # 'Regional Manager', 'Regional Sales Account Manager', 'Regional Sales Executive',
                 # 'Regional Sales Manager', 'Relationship Manager', 'Retail Sales Representative',
                 # 'Retail Store Manager', 'Route Sales Representative',
                 # 'Sales Account Executive, Small and Medium Business', 'Sales and Community Marketing Manager',
                 # 'Sales Assistant', 'Sales Associate', 'Sales Consultant', 'Sales Coordinator', 'Sales Director',
                 # 'Sales Engineer', 'Sales Executive', 'Sales Manager', 'Sales Operation Coordinator',
                 # 'Sales Representative', 'Sales Representative - Territory Lead', 'Sales Trainee', 'Campaign manager',
                 # 'Demand generation manager', 'Director of email marketing', 'Ecommerce content specialist',
                 # 'Ecommerce marketing analyst', 'Ecommerce marketing director', 'Ecommerce marketing manager',
                 # 'Email developer', 'Email marketer', 'Email marketing strategist', 'Email operations manager',
                 # 'Director of market research', 'Insights analyst', 'Market research analyst',
                 # 'Market research interviewer', 'Marketing data analyst', 'Product research analyst',
                 # 'Qualitative research assistant', 'Campaign manager', 'Demand generation manager',
                 # 'Director of email marketing', 'Ecommerce content specialist', 'Ecommerce marketing analyst',
                 # 'Ecommerce marketing director', 'Ecommerce marketing manager', 'Email developer', 'Email marketer',
                 # 'Email marketing strategist', 'Email operations manager', 'Account Coordinator', 'Account Executive',
                 # 'Assistant Account Executive', 'Business Development Analyst', 'Business Development Associate',
                 # 'Business Development Representative', 'Business Development Director', 'Inside Sales Representative',
                 # 'Marketing Associate', 'Outside Sales Representative', 'Regional Account Manager',
                 # 'Regional Sales Manager', 'Relationship Manager', 'Retail Sales Representative', 'Sales Assistant',
                 # 'Sales Associate', 'Sales Consultant', 'Sales Director', 'Sales Engineer',
                 # 'Senior Sales Representative', 'Sales Representative', 'Territory Manager', 'Account Representative',
                 # 'Advertising Sales Representative', 'Automotive Sales Representative', 'Brand Ambassador',
                 # 'Customer Care Representative', 'Direct Salesperson', 'Distribution Sales Representative',
                 # 'Enterprise Sales Representative', 'Equipment Sales Representative', 'Equipment Sales Specialist',
                 # 'Healthcare Sales Representative', 'Industrial Sales Representative', 'Inside Salesperson',
                 # 'Insurance Sales Representative', 'Medical Sales Representative',
                 # 'National Accounts Sales Representative', 'Outside Sales Representative',
                 # 'Retail Sales Representative', 'Route Sales Representative', 'Sales Assistant', 'Sales Associate',
                 # 'Sales Representative', 'Sales Trainee', 'Salesperson', 'Specialty Sales Representative',
                 # 'Territory Sales Representative', 'Account Manager', 'Area Sales Manager',
                 # 'Business Development Manager', 'Direct Sales Manager', 'District Sales Manager',
                 # 'Franchise Development Manager', 'Group Sales Manager', 'Inside Sales Manager',
                 # 'Manager, Business Development', 'Market Development Manager', 'Marketing Manager',
                 # 'National Sales Manager', 'Regional Manager', 'Regional Sales Manager', 'Retail Store Manager',
                 # 'Sales and Community Marketing Manager', 'Sales Manager', 'Territory Manager',
                 # 'Territory Sales Manager', 'Wholesale Sales Manager', 'Business Development Representative',
                 # 'Enterprise Resources Planning Representative', 'Financial Sales Assistant', 'Fixed Income Specialist',
                 # 'Industry Representative', 'Investments Representative', 'National Accounts Sales Analyst',
                 # 'Regional Dealer Recruiter', 'Sales Coordinator', 'Sales Operation Coordinator',
                 # 'Sales Representative - Territory Lead', 'Account Executive', 'Channel Partner Sales Executive',
                 # 'Corporate Sales Account Executive', 'Financial Advisor', 'Financial Planner',
                 # 'Group and Events Sales Coordinator', 'Key Account Manager', 'Major Accounts Manager',
                 # 'National Accounts Sales General Manager', 'Regional Sales Account Manager',
                 # 'Regional Sales Executive', 'Sales Account Executive, Small and Medium Business',
                 # 'Strategic Account Manager', 'Territory Business Manager', 'Wealth Management Advisor',
                 # 'Director of Inside Sales', 'Director of National Sales', 'Director of Sales',
                 # 'Executive Vice President of Sales', 'Frontend Shopify', 'Shopify Developer', 'Full Stack Shopify',
                 # 'Polaris UI Kit Experts', 'GraphQL Experts', 'Shopify integration', 'shopify API', 'Shopify App',
                 # 'shopify engineer', 'shopify programmer', 'Shopify Customization', 'Shopify theme',
                 # 'ECommerce Developer - Shopify', 'Shopify Website', 'Shopify Manager', 'Shopify ecommerce',
                 # 'shopify software', 'Backend Shopify', 'Shopify Intern', 'Liquid Developer', 'Shopify Experience',
                 # 'Shopify Testing', 'Shopify Analyst', 'Shopify Expert', 'Shopify SEO', 'Shopify Designer',
                 # 'Shopify PPC', 'php Shopify', 'Shopify Support', 'Shopify Advisor', 'Web marketing manager',
                 # 'Advertising Art Director', 'Advertising Assistant', 'Advertising Coordinator', 'Advertising Director',
                 # 'Advertising Intern', 'Advertising Manager', 'Advertising Sales Agents',
                 # 'Advertising Sales Representatives', 'Affiliate marketing manager', 'Telemarketer', 'Traffic Manager',
                 # 'Viral or WOM Marketing Specialist', 'Brand Ambassador', 'Brand Assistant',
                 # 'Brand Management Specialist', 'Brand Manager', 'Brand Marketing Associate', 'Brand Strategist',
                 # 'Channel marketing director', 'Communications Assistant', 'Community manager',
                 # 'Consumer Behavior Analyst', 'Content director', 'Content manager', 'Content marketing manager',
                 # 'Content marketing producer', 'Content specialist', 'Content strategist', 'Content writer',
                 # 'copywriter', 'Corporate partnership marketing manager', 'Digital Brand Manager',
                 # 'Digital communications professional', 'Digital Content Manager', 'Digital Content Specialist',
                 # 'Digital Marketing Manager', 'Digital media director', 'Digital strategist', 'Direct Marketer',
                 # 'Brand Activation Manager', 'Director of digital marketing', 'Director of SEO operations',
                 # 'Director of social media', 'Director of social media marketing', 'Director of web marketing',
                 # 'eCommerce Analyst', 'eCommerce Assistant', 'eCommerce Associate', 'eCommerce Content Specialist',
                 # 'eCommerce Coordinator', 'eCommerce Editor', 'eCommerce Fufillment Specialist',
                 # 'eCommerce Marketing Analyst', 'eCommerce Marketing Director', 'eCommerce Marketing Manager',
                 # 'eCommerce Marketing Specialist', 'eCommerce Merchandising Coordinator',
                 # 'eCommerce Merchandising Specialist', 'eCommerce Production Assistant',
                 # 'Email Marketing Manager/Specialist', 'Engagement coordinator', 'Engagement manager',
                 # 'Field Marketing Representative', 'Global Marketing Associate', 'influencer marketing',
                 # 'Integrated Marketing Associate', 'Interactive Marketing Specialist', 'Internet Marketing Manager',
                 # 'Internet marketing specialist', 'Internet Marketing specialist/Coordinator',
                 # 'Junior Project Director', 'Market Analyst', 'Market Development Specialist',
                 # 'Market research Analyst', 'Market Research lead/assistant', 'Market Researcher',
                 # 'Marketing and Promotions Manager', 'Marketing Assistant', 'Marketing Communications Associate',
                 # 'Marketing consultant', 'Marketing Content Assistant', 'Marketing Coordinator',
                 # 'Marketing Data Analyst', 'Marketing Director', 'Marketing Manager', 'Marketing Promotions Specialist',
                 # 'Marketing Technologist', 'Media Assistant', 'Media Buyer', 'Media Director', 'Media Planner',
                 # 'Media Planning Assistant', 'Media Relations', 'Media Researcher',
                 # 'Multi-Media Artist', 'Multimedia communications specialist', 'Office and Administrative Assistants',
                 # 'Online Content Coordinator',
                 # 'Online Product Manager', 'Paid search manager', 'Partner marketing advisor',
                 # 'Partnership marketing director',
                 # 'Partnership marketing manager', 'Pay-per-click manager', 'Product Development Associate',
                 # 'Product Manager',
                 # 'Product Marketing Associate', 'Product Marketing Manager', 'Product Promoters', 'Production Worker',
                 # 'Project Manager', 'Promotions Assistant', 'Promotions Coordinator', 'Promotions Director',
                 # 'Promotions Manager', 'Purchasing Agent', 'Research Executive', 'Retention Marketing Specialist',
                 # 'Senior Brand Manager', 'Senior Product Manager', 'SEO manager', 'SEO Specialist',
                 # 'Social media manager', 'Social media Marketing', 'Social Media specialist', 'Strategy Consultant',
                 # 'Survey Researcher', 'Digital marketing manager', 'Digital strategist',
                 # 'Director of digital marketing', 'Director of web marketing', 'Director of SEO operations',
                 # 'Internet marketing specialist', 'Internet marketing specialist', 'Paid search manager',
                 # 'Pay-per-click manager', 'SEM manager', 'SEM specialist', 'SEO manager', 'SEO specialist',
                 # 'Web marketing manager', 'Web marketing specialist', 'Community manager',
                 # 'Digital communications professional', 'Digital media director', 'Director of social media',
                 # 'Director of social media marketing', 'Engagement coordinator', 'Engagement manager',
                 # 'Multimedia communications specialist', 'Social media editor', 'Social media manager',
                 # 'Social media marketing manager', 'Social media strategist', 'Affiliate marketing manager',
                 # 'Channel marketing director', 'Corporate partnership marketing manager',
                 # 'Director of influencer marketing and partnerships', 'Partner marketing advisor',
                 # 'Partnership marketing director', 'Partnership marketing manager',
                 # 'Content director', 'Content manager', 'Content marketing manager', 'Content marketing producer',
                 # 'Content specialist',
                 # 'Content strategist', 'Content writer', 'Digital marketing manager', 'Digital strategist',
                 # 'Director of digital marketing',
                 # 'Director of web marketing', 'Director of SEO operations', 'Internet marketing specialist',
                 # 'Internet marketing specialist',
                 # 'Paid search manager', 'Pay-per-click manager', 'SEM manager', 'SEM specialist', 'SEO manager',
                 # 'SEO specialist',
                 # 'Web marketing manager', 'Web marketing specialist', 'Advertising Director', 'Account Coordinator',
                 # 'Account Executive',
                 # 'Advertising Manager', 'Art Director', 'Copywriter', 'Creative Assistant', 'Creative Director',
                 # 'Marketing Promotions Specialist',
                 # 'Media Buyer', 'Media Assistant', 'Media Planning Assistant', 'Media Director', 'Media Planner',
                 # 'Media Researcher', 'Project Manager',
                 # 'Junior Project Director', 'Promotions Director', 'Promotions Assistant', 'Promotions Coordinator',
                 # 'Promotions Manager',
                 # 'Creative Marketing Assistant', 'Advertising Intern', 'Advertising Coordinator',
                 # 'Advertising Assistant', 'Marketing Assistant', 'Assistant Media Buyer', 'Traffic Manager',
                 # 'Advertising Sales Representatives', 'Junior Copywriter', 'Senior Copywriter', 'Copywriter Intern',
                 # 'Creative Advertising Intern', 'Digital Advertising Intern', 'Assistant Account Executive',
                 # 'Graphic Designer', 'Junior Graphic Designer', 'Marketing and Promotions Manager',
                 # 'Advertising Art Director', 'Advertising Sales Agents', 'Animator', 'Brand Management Specialist',
                 # 'Consumer Behavior Analyst', 'Copywriter', 'Creative Director', 'Database Marketing Specialist',
                 # 'Demonstrators', 'Direct Marketer', 'Email Marketing Specialist', 'Event and Trade Show Marketer',
                 # 'Field Marketing Representative', 'Global Marketing Associate', 'Graphic Designer',
                 # 'Integrated Marketing Associate', 'Interactive Marketing Specialist', 'Internet Marketing Specialist',
                 # 'Market Analyst', 'Market Development Specialist', 'Market Research Analyst', 'Market Researcher',
                 # 'Marketing Communications Associate', 'Marketing Coordinator', 'Media Buyer', 'Media Director',
                 # 'Media Planner', 'Multi-Media Artist', 'Office and Administrative Assistants',
                 # 'Product Development Associate', 'Product Marketing Associate', 'Product Promoters',
                 # 'Production Worker', 'Promotions Manager', 'Purchasing Agent', 'Research Executive',
                 # 'Retail Merchandise Displayer', 'Retention Marketing Specialist', 'SEO Specialist',
                 # 'Survey Researcher', 'Telemarketer', 'Viral or WOM Marketing Specialist', 'Content Creator',
                 # 'Content Strategist', 'Content Marketing Manager', 'Creative Assistant', 'Digital Brand Manager',
                 # 'Creative Director', 'Marketing Data Analyst', 'Marketing Technologist', 'Digital Marketing Manager',
                 # 'Social Media Coordinator', 'Social Media Strategist', 'Community Manager', 'SEO Specialist',
                 # 'SEO Strategist', 'SEO/Marketing Manager', 'Assistant Brand Manager', 'Assistant Product Manager',
                 # 'Associate Brand Manager', 'Brand Assistant', 'Brand Manager', 'Brand Strategist',
                 # 'Senior Product Manager', 'Product Manager', 'Product Marketing Manager', 'Senior Brand Manager',
                 # 'Brand Marketing Specialist', 'Brand Marketing Representative', 'Brand Marketing Manager',
                 # 'Assistant Brand Marketing Manager', 'Brand Marketing Associate', 'Junior Brand Manager',
                 # 'Brand Activation Manager', 'Brand Marketing Intern', 'Marketing Assistant',
                 # 'Brand Marketing Associate', 'Content Marketing Manager', 'Content Writer', 'Digital Brand Manager',
                 # 'Digital Marketing Manager', 'Director of Digital Marketing', 'Internet Marketing Coordinator',
                 # 'Internet Marketing Director', 'Internet Marketing Specialist', 'SEO Manager',
                 # 'Social Media Marketing Analyst', 'Social Media Marketing Coordinator',
                 # 'Social Media Marketing Manager', 'Content Marketing Specialist', 'Marketing Content Writer',
                 # 'Social Media Marketing Intern', 'Web Content Marketing Specialist', 'Online Marketing Assistant',
                 # 'Content marketing Coordinator', 'Marketing Assistant', 'Digital Content Specialist',
                 # 'Content Marketing Producer', 'Marketing Content Assistant', 'Content Marketing Intern',
                 # 'Marketing and Promotions Manager', 'Marketing Promotions Specialist', 'Marketing Specialist',
                 # 'Marketing Assistant', 'Marketing Associate', 'Direct Marketing Manager',
                 # 'Analyst Performance Marketing', 'Database Marketing Analyst', 'Direct Marketing Specialist',
                 # 'Direct Marketing Representative', 'Direct Marketing Intern', 'Direct Mail Coordinator',
                 # 'Digital Marketing Specialist', 'Direct Marketing Coordinator', 'Digital Marketing Associate',
                 # 'Direct Marketing Analyst', 'Assistant Director, Direct Marketing', 'Operations Assistant',
                 # 'Vice President for Marketing', 'Marketing Director', 'Assistant Marketing Director',
                 # 'Associate Marketing Director', 'Marketing Manager', 'Business Development Representative',
                 # 'Communications Assistant', 'Corporate Communications Specialist',
                 # 'Corporate Communications Coordinator', 'Marketing Communications Coordinator',
                 # 'Marketing Communications Director', 'Marketing Communications Manager',
                 # 'Marketing Communications Specialist', 'Marketing Consultant', 'Corporate Communications Assistant',
                 # 'Marketing Coordinator', 'Media Relations Coordinator', 'Media Relations Director',
                 # 'Media Relations Associate', 'Outside Sales Representative', 'Public Relations Assistant',
                 # 'Public Relations Coordinator', 'Public Relations Director', 'Public Relations Manager',
                 # 'Public Relations Representative', 'Public Relations Specialist', 'Publicity Assistant',
                 # 'Publicity Director', 'Publicity Manager', 'Public Relations Intern',
                 # 'Corporate Communications Intern', 'eCommerce Marketing Director', 'eCommerce Marketing Manager',
                 # 'eCommerce Marketing Specialist', 'eCommerce Content Specialist', 'eCommerce Editor',
                 # 'eCommerce Associate', 'eCommerce Coordinator', 'eCommerce Fufillment Specialist',
                 # 'eCommerce Marketing Analyst', 'eCommerce Analyst', 'eCommerce Assistant',
                 # 'eCommerce Merchandising Specialist', 'eCommerce Production Assistant',
                 # 'eCommerce Merchandising Coordinator', 'Email Marketer', 'Online Product Manager', 'Business Analyst',
                 # 'Consulting Advisor', 'Creative Consultant', 'Educational Consultant',
                 # 'Government Contract Consultant', 'Implementation Consultant', 'International Consultant',
                 # 'Lead Consulting Engineer', 'Management Consultant', 'Organizational Development Consultant',
                 # 'Political Strategist', 'Strategy Consultant', 'Blogger', 'Brand Ambassador', 'Brand Manager',
                 # 'Community Manager', 'Content Manager', 'Content Strategist', 'Digital Communications Professional',
                 # 'Digital Content Manager', 'Digital Media Manager', 'Digital Media Producer',
                 # 'Digital Media Supervisor', 'Director of Community', 'Director, Communications Planning',
                 # 'Director, Online Communications', 'Director, Social Marketing and Brand Communications',
                 # 'Director, Social Media Marketing', 'Director of Social Media',
                 # 'Director of Social Media Communications', 'Director, Social Media Relations',
                 # 'Director of Social Media Strategy', 'Engagement Coordinator', 'Engagement Manager',
                 # 'Interactive Media Associate', 'Interactive Media Coordinator', 'Interactive Media Manager',
                 # 'Internet Marketing Coordinator', 'Internet Marketing Manager', 'Manager of Digital and Social Media',
                 # 'Manager, Social Media', 'Multi-Media Communications Specialist', 'Online Content Coordinator',
                 # 'Social Media Account Executive', 'Social Media Analyst', 'Social Media Assistant',
                 # 'Social Media Associate', 'Social Media Coordinator', 'Social Media Designer', 'Social Media Editor',
                 # 'Social Media Executive', 'Social Media Marketing Coordinator', 'Social Media Manager',
                 # 'Social Media Producer', 'Social Media Specialist', 'Amazon Docker', 'AWS Architect', 'AWS Big Data',
                 # 'AWS Cloud Architect', 'AWS Cloud Engineer', 'AWS Data Engineer', 'AWS DevOps ', 'AWS Infrastructure',
                 # 'AWS Security', 'AWS Solutions', 'AWS SysOps', 'AWS Networking', 'AWS Redshift', 'AWS Integrator',
                 # 'DevOps Security', 'Data Solutions', 'AWS Enterprise', 'Cloud Solutions', 'Cloud Developer',
                 # 'AWS Software', 'Azure Enginner', 'Full Stack AWS', 'Linux AWS', 'AWS Engineer',
                 # 'AWS Solutions Architect', 'DevOps Engineer', 'Big Data AWS', 'ASP.net Core Developer',
                 # 'Staff AWS Engineer', 'Systems Engineer', 'Quantum Computing', 'Embedded Development',
                 # 'Senior Big Data Architect', 'Principal Solutions Architect', 'Consultant Marketing Cloud',
                 # 'Heroku Salesforce Developer', 'Junior Salesforce Developer', 'Lead Salesforce Technical Architect',
                 # 'Remote Salesforce Administrator', 'Remote Salesforce Developer', 'Salesforce Administrator',
                 # 'salesforce analyst', 'Salesforce Architect', 'Salesforce Business Analyst',
                 # 'salesforce certified platform developer', 'Salesforce Commerce Cloud Developer',
                 # 'Salesforce CPQ Administrator', 'Salesforce Developer',
                 # 'Salesforce Development Team Lead', 'Salesforce Functional Consultant', 'Salesforce Lead Developer',
                 # 'salesforce patron manager', 'salesforce patronmanager',
                 # 'Salesforce Marketing Cloud Technical Architect', 'Salesforce Platform Manager',
                 # 'salesforce programmer', 'Salesforce Remote Lightning Developer', 'Salesforce Solution Architect',
                 # 'Salesforce Technical Architect', 'Salesforce Vlocity Developer',
                 # 'Senior Data Storage Architect with SalesForce Experience', 'Senior Salesforce Developer',
                 # 'Salesforce Quality assurance lead', 'salesforce trainer', 'Business System Analyst',
                 # 'Project Manager', 'Commercial Account Manager', 'Digital Strategy Lead - Salesforce',
                 # 'Salesforce Solution Lead', 'CRM Campaign specialist', 'CRM specialist', 'Salesforce Delivery Manager',
                 # 'Salesforce Program Director', 'QA Test Analyst - Salesforce', 'Salesforce technical lead',
                 # 'customer support', 'customer service', 'Call Center', 'Email Support', 'Chat Assistant',
                 # 'Chat Support', 'Client Service', 'Communications Professional', 'Contact Center',
                 # 'Custodial Customer', 'Customer Care Agent', 'customer experience', 'Interaction Management',
                 # 'Customer Liaison', 'Customer Relations', 'Customer Retention', 'Customer Associate',
                 # 'customer consultant', 'customer success', 'Technical Service', 'Technical Support ',
                 # 'Customer Manager', 'Customer Representative', 'Customer Specialist', 'Customer Supervisor',
                 # 'Customer Coordinator', 'Customer Associate', 'Customer Director', 'Customer Service Rep',
                 # 'Customer Engineer', 'Customer Technician', 'Customer Lead', 'Telemarketing Manager',
                 # 'Inbound Support', 'Telemarketing Specialist', 'Customer Trainer', 'Senior Support',
                 # 'Support and Community', 'Technical Support ', 'Support Specialist', 'Support Agent',
                 # 'Customer Advocacy', 'Client Success', 'Client Support Officer', 'Customer Engagement',
                 # 'Customer Support Advisor', 'Customer Guru', 'Vaccination Support', 'Phone Campaigns',
                 # 'Cloud Architect', 'Cloud Consultant', 'Cloud Developer', 'cloud engineer',
                 # 'Infrastructure, google cloud', 'Cloud Manager', 'Cloud Security', 'Cloud Technical Solutions',
                 # 'Enterprise google Cloud', 'Systems Engineer Cloud', 'Cloud SQL', 'Cloud Analyst', 'Cloud Platform',
                 # 'Google Cloud Architect', 'Google Cloud Developer', 'Google Cloud Engineer', 'Big Data Engineer',
                 # 'Cloud Infrastructure', 'Cloud Support', 'Google Cloud Dataflow', 'Cloud Operations',
                 # 'Intelligence Designer', 'Machine Learning', 'Robotics Process Analyst', 'AI Interaction',
                 # 'Conversational AI', 'AI Robotics', 'Senior Research', 'Development Engineer', 'Machine Design',
                 # 'Machine Researcher', 'Equity Research', 'AI/ML Engineer', 'Data Scientist', 'AI Programmer',
                 # 'Lead AI', 'AI Development', 'Data Science', 'AI Success', 'Risk and Analytics', 'AI Expert',
                 # 'Intelligence Analyst', 'Big Data & AI Researcher', 'AI Researcher', 'AI Consultant ', 'AI Scientist',
                 # 'AI Experience', 'AI Operations', 'Algorithm Development', 'AI Business Analyst', 'Cyber AI',
                 # 'Data Architect', 'AI Specialist', 'AI Intern', 'Cognitive Scientist', 'Cognitive Engineer',
                 # 'AI Learning Engineer', 'Data Evangelist', 'AI Analyst', 'AI Solutions Architect', 'AI Deep Learning',
                 # 'Senior Data Engineer', 'Principal AI Researcher', 'AI Full Stack', 'Intelligence Engineer',
                 # 'AI Data Engineer', 'AI Evangelist', 'ML Evangelist', 'AI Developer', 'Advanced AI Analytics',
                 # 'AI Technical Advisor', 'Data Engineer', 'Data Analyst'
                 ]