sample_cat = {
    'website Development': ['WordPress Developer', 'WordPress Theme Developer', 'WordPress Plugin Developer', 'WordPress Frontend Developer',
                            'WordPress Backend Developer', 'WordPress Theme Designer', 'WordPress Consultant', 'WordPress Support Engineer',
                            'Joomla Developer', 'Joomla Frontend Developer', 'Joomla Template Developer', 'Joomla Extension Developer',
                            'Joomla Site Builder', 'Joomla Consultant', 'Joomla Architect', 'Joomla Support Engineer',
                            'Drupal Developer', 'Drupal Frontend Developer', 'Drupal Backend Developer', 'Drupal Module Developer', 'Drupal Site Builder'
                            'Drupal Consultant', 'Drupal Architect', 'Drupal Support Engineer', 'Contentful Developer', 'HTML/CSS Developer', 'Frontend Developer',
                            'Webmaster', 'Web Administrator', 'Web Analyst', 'Web Architect', 'Web Consultant', 'Web Coordinator', 'Web Editor',
                            'Web Integrator', 'Web Services Developer', 'Web Accessibility Specialist', 'Performance Optimization Specialist'],

    'Web App Development / Javascript': ['Angular Developer', 'Angular Frontend Developer', 'Angular UI Developer', 'Angular Architect', 'Angular Consultant',
                                         'Angular Team Lead', 'Angular Full stack Developer', 'React Developer', 'ReactJS Developer', 'React Frontend Developer',
                                         'React UI Developer', 'React Architect', 'React Consultant', 'React Team Lead', 'React Full stack Developer',
                                         'Vue.js Developer', 'Vue.js Frontend Developer', 'Vue.js UI Developer', 'Vue.js Architect', 'Vue.js Consultant',
                                         'Vue.js Team Lead', 'Vue.js Full stack Developer', 'Ember.js Developer', 'Ember.js Frontend Developer', 'Ember.js UI Developer',
                                         'Ember.js Architect', 'Ember.js Consultant', 'Ember.js Team Lead', 'Ember.js Full stack Developer', 'Backbone.js Developer',
                                         'Backbone.js Frontend Developer', 'Backbone.js UI Developer', 'Backbone.js Architect', 'Backbone.js Consultant', 'Backbone.js Team Lead',
                                         'Backbone.js Full stack Developer', 'Meteor.js Developer', 'Meteor.js Full-stack Developer', 'Meteor.js Consultant', 'Meteor.js Team Lead',
                                         'Node.js Developer', 'Node.js Backend Developer', 'Node.js Architect', 'Node.js Consultant', 'Node.js Team Lead', 'Node.js Full stack Developer',
                                         'NEXT.js Developer', 'NEXT.js Architect', 'NEXT.js Consultant', 'NEXT.js Team Lead', 'NEXT.js Full stack Developer', 'JavaScript Developer',
                                         'Web Application Developer', 'Web App Developer', 'TypeScript Developer', 'jQuery Developer', 'Web Services Developer',
                                         'RESTful API Developer', 'SOAP Developer', 'Frontend Architect', 'Responsive Web Developer', 'Progressive Web App (PWA) Developer',
                                        
                                         ],
    'Backend Engineering': ['.NET Developer', 'ASP.NET Developer', 'C# Developer', 'VB.NET Developer', 'Windows Forms Developer', 'WPF Developer', 'ASP.NET MVC Developer',
                            'Entity Framework Developer', 'ASP.NET Backend Developer', 'ASP.NET Architect', 'ASP.NET Consultant', 'ASP.NET Team Lead', 'ASP.NET Full Stack Developer',
                            'ASP.NET Developer', 'ASP.NET Engineer', 'Java Developer', 'J2EE Developer', 'Spring Framework Developer', 'Hibernate Developer', 'JavaFX Developer',
                            'Java Swing Developer', 'Java Architect', 'Java Full Stack Developer', 'Java Web Services Developer', 'Java Enterprise Developer', 'Python Developer',
                            'Django Developer', 'Flask Developer', 'Python Full Stack Developer', 'Python Web Developer', 'Python Scripting Developer', 'Scientific Computing Developer (Python)',
                            'SQL Developer', 'Database Administrator (DBA)', 'Data Engineer', 'Database Architect', 'Database Analyst', 'Data Warehouse Developer',
                            'Business Intelligence Developer', 'ETL Developer', 'Oracle Developer', 'MySQL Developer', 'PostgreSQL Developer', 'MongoDB Developer', 'SQL Engineer',
                            'Database Developer', 'Ruby on Rails Backend Developer', 'Ruby on Rails Architect', 'Ruby on Rails Consultant', 'Ruby on Rails Team Lead', 'Ruby on Rails Full stack Developer',
                            'Ruby Developer', 'Ruby on Rails Developer', 'Ruby Full Stack Developer', 'Ruby Web Developer', 'Ruby API Developer', 'Ruby Scripting Developer',
                            'Ruby Consultant', 'Django Backend Developer', 'Django Architect', 'Django Consultant', 'Django Team Lead', 'Django Full Stack Developer',
                            'Flask Backend Developer', 'Flask Architect', 'Flask Consultant', 'Flask Consultant', 'Flask Team Lead', 'Flask Full Stack Developer', 'PHP Developer',
                            'Laravel Developer', 'Symfony Developer', 'CodeIgniter Developer', 'PHP Full Stack Developer', 'PHP Web Developer', 'PHP Architect', 'PHP Consultant',
                            'Custom PHP Developer', 'API Developer', 'Integration Engineer', 'API Architect', 'API Engineer', 'Integration Programmer', 'Integration Support Engineer',
                            ],
    'Mobile App Development': ['iOS Developer', 'Swift Developer', 'Objective-C Developer', 'Android Developer', 'Kotlin Developer', 'Java Developer',
                               'React Native Developer', 'Flutter Developer', 'Dart Developer', 'Xamarin Developer', 'Mobile App Engineer',
                               'Mobile Application Engineer', 'Mobile App Developer', 'Mobile Application Developer', 'Mobile Architect', 'Mobile Game Developer',
                               'Mobile Architect', 'Mobile App Architect', 'Cross-Platform App Developer', 'Hybrid Mobile App Development',
                               'Mobile Performance Engineer', 'Mobile Security Specialist', 'Mobile Support Engineer'],
    'General Engineering': ['Software Engineer', 'Custom Software Developer', 'Solutions Architect', 'Application Developer', 'App Developer', 'Desktop Application Architect',
                            'Desktop Application Developer', 'Windows Application Developer', 'Linux Application Developer', 'macOS Application Developer', 'Enterprise Software Developer',
                            'Systems Analyst', 'Enterprise Integration Architect', 'Enterprise Software Consultant', 'Enterprise Software Support Engineer', 'Enterprise Architect',
                            'Enterprise Integration Specialist', 'Enterprise Security Developer', 'Software Architect', 'Typescript Developer', 'Application Support Engineer',
                            'Technical Support Engineer', 'Software Maintenance Engineer', 'Support Specialist', 'Support Analyst', 'Support Consultant', 'Support Coordinator', 'Support Manager',
                            'Support Team Lead', 'Application Support Specialist', 'Application Support Analyst', 'Application Support Consultant',
                            'Application Support Coordinator', 'Application Support Manager', 'Technical Support Specialist',
                            'Technical Support Analyst', 'Technical Support Analyst', 'Technical Support Coordinator',
                            'Technical Support Manager', 'Maintenance Engineer', 'Maintenance Specialist', 'Maintenance Coordinator',
                            ],

    'AI/ML': ['Data Analyst', 'Data Visualization Developer', 'Data Warehousing Specialist', 'Data Mining Specialist', 'Data Modeller', 'Data Consultant', 'Data Product Evangelist', 'Data Specialist',
              'Data Scientist Machine Learning', 'Data Strategist', 'Data Protection Technical Advisor', 'Data Quality Analyst', 'Data Scientist', 'Data Analyst/scientist', 'Big Data Architect', 'Big Data Analytics / Etl Developer', 'Big Data Engineer', 'Business Intelligence Developer', 'Business Intelligence Analyst', 'Business Analytics Consultant', 'ETL Developer', 'Data Governance Specialist', 'Predictive Analytics Developer', 'Business Intelligence Bi Consultant', 'Enterprise Data Architect', 'Ai/ml Architect', 'Machine Learning Researcher', 'Ai Conversational Designer',
              'Machine Design Engineer', 'Scientific Data Analyst / Algorithms Researcher', 'Developer Business Intelligence', 'Principle Data Scientist Machine Learning', 'AI Researcher', 'Business Intelligence Bi Analyst', 'Big Data/hadoop Developer', 'Competitive Intelligence Analyst', 'Ai/ml Engineer', 'Solutions Consultant Ai', 'Bi And Data Analyst', 'Machine Learning Specialist',
              'AI Scientist', 'Business Intelligence', 'Principle Data Architect', 'Data/business Intelligence Analyst', 'Business Data Analyst', 'Machine Vision Application Engineer', 'Machine Vision Application Engineer', 'Machine Learning Engineer', 'Machine Learning Research Engineer', 'AI Engineer', 'Deep Learning Engineer', 'Machine Design', 'Machine Researcher', 'AI Programmer',
              'Lead AI', 'AI Developer', 'Data Scientist ', 'AI Success', 'Risk and Analytics', 'AI Expert', 'Intelligence Analyst', 'Big Data & AI Researcher', 'AI Consultant', 'AI Experience',
              'AI Operations', 'Algorithm Development', 'AI Business Analyst', 'Cyber AI', 'Data Architect', 'AI Specialist', 'AI Intern', 'Cognitive Scientist', 'Cognitive Engineer', 'AI Learning Engineer', 'Data Evangelist', 'AI Analyst', 'AI Solutions Architect', 'AI Deep Learning', 'Senior Data Engineer', 'Principal AI Researcher', 'AI Full Stack', 'Intelligence Engineer', 'AI Data Engineer', 'AI Evangelist', 'ML Evangelist', 'AI Developer', 'Advanced AI Analytics', 'AI Technical Advisor'],

    'Ecommerce Experts': ['Magento Developer', 'Magento Frontend Developer', 'Magento Backend Developer', 'Magento Theme Developer', 'Magento Extension Developer', 'Magento Consultant', 'Magento Architect',
                          'Magento Support Engineer', 'WooCommerce Developer', 'WooCommerce Theme Developer', 'WooCommerce Plugin Developer', 'WooCommerce Frontend Developer', 'WooCommerce Backend Developer',
                          'WooCommerce Consultant', 'WooCommerce Support Engineer', 'PrestaShop Developer', 'BigCommerce Developer', 'OpenCart Developer', 'Hybris Developer', 'E-commerce Architect', 'Shopping Cart Developer', 'Order Management Developer', 'E-commerce Analytics Developer', 'E-commerce Developer', 'Online Store Developer', 'E-commerce Consultant', 'E-commerce Programmer', 'E-commerce Support Engineer', 'E-commerce Systems Analyst'],
    'QA': ['QA Analyst', 'QA Consultant', 'QA Manager', 'QA Architect', 'QA Automation Specialist', 'QA Performance Engineer', 'QA Security Engineer', 'QA Test Data Engineer', 'QA Test Planning Engineer',
           'QA Test Strategy Manager', 'QA Test Reporting Specialist', 'Quality Assurance Engineer', 'QA Automation Engineer', 'Software Tester', 'Test Automation Engineer', 'Automation Engineer'],

    'Management': ['Project Manager', 'Techinical Project Manager ', 'Scrum Master ', 'Project Manager ', 'Product Owner ', 'IT Manager'],

    'NoCode Web Development': ['Wix Developer', 'Wix Website Designer', 'Wix App Developer', 'Wix Front-end Developer', 'Wix Template Designer', 'Wix Consultant', 'Wix Support Engineer', 'Squarespace Developer',
                               'Squarespace Website Designer', 'Squarespace Template Developer', 'Squarespace Front-end Developer', 'Squarespace Consultant', 'Squarespace Support Engineer',
                               'Weebly Developer', 'Weebly Website Designer', 'Weebly Template Developer', 'Weebly Front-end Developer', 'Weebly Consultant', 'Weebly Support Engineer',
                               'Webflow Developer', 'Webflow Website Designer', 'Webflow Template Developer', 'Webflow Front-end Developer', 'Webflow Consultant', 'Webflow Support Engineer', 'Webflow Designer'],

    'GCP': ['Google Cloud Architect', 'Google Cloud Engineer', 'Google Cloud Consultant', 'Google Cloud Platform Architect', 'Google Cloud Instructor'],

    'AWS': ['Amazon Docker', 'AWS Architect', 'AWS Big Data', 'AWS Cloud Architect', 'AWS Cloud Engineer', 'AWS Data Engineer', 'AWS DevOps', 'AWS Infrastructure', 'AWS Security', 'AWS Solutions', 'AWS SysOps',
            'AWS Networking', 'AWS Redshift', 'AWS Integrator', 'AWS Enterprise', 'AWS Solutions Architect', 'Big Data AWS', 'Azure Cloud Infrastructure Engineer', 'Aws Developer', 'Lead Developer Aws Cloud',
            'Aws Connect Architect Developer', 'Devsecops / Aws Operations Engineer', 'Security Engineer Aws', 'Aws Sysops Devops Architect', 'Devops/aws Engineer', 'Aws Big Data Engineer', 'Aws Platform Engineer/devops',
            'Aws Devops Engineer'],
    #
    'Salesforce Development': ['Salesforce Administrator', 'Salesforce Consultant', 'Salesforce Architect', 'Salesforce Lightning Developer', 'Salesforce Integration Developer', 'Salesforce CPQ Developer',
                               'Salesforce Marketing Cloud Developer', 'Salesforce Commerce Cloud Developer', 'Salesforce Community Cloud Developer', 'Salesforce Service Cloud Developer', 'Salesforce Data Analyst',
                               'Salesforce Data Migration Specialist', 'Salesforce Business Analyst', 'Salesforce Solution Architect', 'Salesforce Data Specialist', 'Salesforce Admin Support Analyst',
                               'Salesforce Marketo Admin', 'Salesforce Engineer', 'Implementation Consultant Salesforce', 'Salesforce Commercial Operations Manager', 'Salesforce Functional Consultant',
                               'Salesforce Technical Product Owner', 'Salesforce Analyst', 'Lightning Salesforce Developer', 'Salesforce Developer'],

    'Shopify Custom Development': ['Shopify Developer', 'Shopify Theme Developer', 'Shopify App Developer', 'Shopify Front-end Developer', 'Shopify Store Setup Specialist', 'Shopify Consultant',
                                   'Shopify Support Engineer'],

    'General Design': ['ART Director', 'Branding And Packaging Designer', ' Creative Designer', 'Design Director', 'Design Lead', 'Designer/multimedia Specialist', 'Multimedia Specialist', 'Digital Designer',
                       'Director Of Design', 'Intermediate Designer', 'Multimedia Content Designer', 'Multimedia Designer', 'Principal Designer', 'Visual Designer', 'Design Specialist', 'Digital Designer',
                       'Visual Communicator', 'Data Visualization Specialist' 'Visual Storyteller', 'Creative Director', 'Creative Coordinator', 'Design Manager', 'Design Director', 'Design Team Lead'],

    'Branding': ['Brand Strategist', 'Branding Expert', 'Visual Identity Designer', 'Branding Designer', 'Logo Designer', 'Brand Designer', 'Brand Identity Specialist', 'Brand Strategist',
                 'Corporate Identity Designer', 'Brand Experience Designer', 'Brand Identity Developer'],

    'UI/UX': ['Advanced Ux Researcher', 'App Designer', 'Associate Product Designer', 'Digital Product Designer', 'Front-End Designer', 'Graduate Ux Designer', 'Intermediate ui', 'Intermediate ux',
              'Mobile Designer', 'Mobile Interaction Designer', 'Mobile Interface Designer', 'Mobile UI Designer', 'Mobile User Experience Designer', 'Mobile User Interface Designer', 'Product Designer',
              'UI Designer', 'UI Product Designer ', 'User Experience (UX) Designer', 'User Interface (UI) Designer', 'UX Designer', 'UX Product Designer', 'UX User Designer', 'UX/UI Artist', 'UX/UI Artist',
              'UX/UI Designer', 'Web Designer', 'Web Designer / Data Visualization Analyst', 'Webflow Designer', 'UI/UX Designer', 'UX Designer', 'Interaction Designer', 'Information Architect',
              'Usability Specialist', 'User Researcher', 'User Interface Designer', 'Product Designer', 'Service Designer', 'UX Researcher', 'UX Strategist', 'Email Marketing Designer', 'Interactive Designer'],

    'Graphic Design': ['Content Designer', 'Design Associate', 'Graphic Designer', 'Packaging Designer', 'Social Media Graphic Designer', 'Senior Graphic Designer ', 'Visual Communication Designer',
                       'Print Designer', 'Digital Designer', 'Presentation Designer', 'Packaging Designer', 'Print Designer', 'Print Specialist', 'Packaging Designer', 'Social Media Designer',
                       'Presentation Designer', 'Slidedeck Designer'],

    'Animation and Motion Designer': ['3D Animator', '3D Designer', '3D Design Associate', '2D Animator', '2D Designer', '2D Desgin Associate', '2D/3D Animator', '2D/3D DesignerI', '2D/3D Design Associate',
                                      'Animation Director ', 'Animator', 'Lead Animator', 'Motion Designer', 'Motion Graphic Designer', 'Social Motion Digital Designer', 'Social Motion Digital Animator',
                                      'Video Editor Multimedia Designer', 'Visual Effects Artist', 'Storyboard Artist', 'Motion Graphics Designer'],

    'LiveLeads': ['Demand Generation Manager',  'Demand Generation Specialist', 'Lead Research Representative', 'Lead Researcher', 'Lead Generation Specialist', 'Lead Management',
                  'Lead Nurturing', 'Lead Qualification', 'Lead Research', 'Sales Lead Generation', 'Lead Generation Specialist', 'Lead Generation Manager (Digital)', 'Lead Generation Specialist',
                  'Lead Qualification Representative', 'Data Researcher', 'Lead Generation Manager', 'Lead Nurturing Specialist', 'Lead Analyst'],

    'B2B Growth': ['Account Coordinator', 'Account Director', 'Account Executive', 'Account Executive / Account Manager', 'Account Executive Financial Services', 'Account Executive Partnership Marketing',
                   'Account Manager', 'Account Manager Client Success', 'Account Manager/strategist Social And Content', 'Account Representative', 'Account Specialist', 'Accounting Manager', 'Scheduling Manager',
                   'Email Developer', 'Email Marketing', 'Email Marketing Account Manager', 'Email Marketing Coordinator', 'Email Marketing Manager', 'Email Marketing Specialist', 'Email Specialist',
                   'Digital Automotive Account Manager', 'Digital Account Manager', 'Digital Marketing Account Manager', 'Business Development Manager', 'Digital Marketing Account Manager',
                   
                   ],

    'General Sales': ["Admin Sales", "Sales Account Executive", "Sales Admin", "Sales Advisor", "Sales And Catering Manager", "Sales And Community Development Manager", "Sales And Marketing Manager", "Sales Assistant",
                      "Sales Associate", "Sales Consultant", "Sales Coordinator", "Director of Sales", "Sales Engineer", "Sales Director", "sales executive", "Sales Manager", "Sales Marketing", "Sales Operation",
                      "Sales Operations Manager", "Sales Ops Engineer", "Sales Professional", "Sales Service Representative", "Sales Specialist", "Sales Support Specialist", "B2B Sales", "Sales Associate",
                      "Junior Sales Representative", "Marketing and Sales Coordinator",
                      "Sales Engineer", "Channel Sales Manager", "Sales Operations Analyst", "Senior Sales Representative", "National Sales Manager", "Regional Sales Manager", "Sales Enablement Manager",
                      "Customer Success Manager", "Commercial Manager", "Software Sales", "Specialty Sales", "Crm Manager", "It Technical Sales Apprentice", "Vice President of Sales", "Digital Manager", "Digital Manager", "Digital Marketing Sales Analyst", "Direct Sales", "Director Of Sales", "Distribution Sales", "District Sales", "Manager Business Solutions", "Marketing Assistant/sales Proposal Designer",
                      ]

}
